name: flutter_string_encryption
description: Cross-platform string encryption using common best-practices.
version: 0.3.1

homepage: https://github.com/sroddy/flutter_string_encryption

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.sroddy.flutterstringencryption
    pluginClass: FlutterStringEncryptionPlugin
